[build]
    command = "npm run build && npm run export"
    publish = "out"

[[redirects]]
  from = "/api/*"
  to = "https://chat.air.ai/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200    